# Generated by Django 2.2.17 on 2021-01-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210128_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='king',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
